import Link from "next/link";
import { BarChart3, Boxes, ChevronRight, CircleHelp, FileCode2, LogOut, Package, ReceiptText, Settings, ShieldCheck, Truck, UserRound } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { SectionCard } from "@/components/ui/section-card";

const groups = [
  { title: "Operasional", items: [["/products", "Produk", "Kelola katalog dan harga", Package, "blue"], ["/delivery", "Pengiriman", "Rute, driver, dan POD", Truck, "green"], ["/receivables", "Piutang & Pembayaran", "Aging dan penagihan", ReceiptText, "yellow"], ["/tax-xml", "Pajak XML", "Validasi dan ekspor Coretax", FileCode2, "purple"]] },
  { title: "Analitik & Sistem", items: [["/reports", "Laporan", "Penjualan, stok, dan keuangan", BarChart3, "blue"], ["/settings", "Pengaturan", "Tenant, branding, dan modul", Settings, "gray"]] },
] as const;
export default function MorePage() { return <><PageHeader eyebrow="Menu" title="Lainnya" description="Akses cepat ke seluruh modul distributor." /><SectionCard><div className="profile-card"><div className="profile-avatar">MW</div><div><strong>Mrs Wang</strong><span>Owner / Admin Distributor</span><small><ShieldCheck size={11} /> AICE Distributor · Pilot Pro</small></div><Link href="/settings"><ChevronRight /></Link></div></SectionCard>{groups.map((group) => <SectionCard key={group.title} title={group.title}><div className="more-menu">{group.items.map(([href, label, description, Icon, tone]) => <Link href={href} key={href}><i className={`menu-${tone}`}><Icon /></i><span><strong>{label}</strong><small>{description}</small></span><ChevronRight /></Link>)}</div></SectionCard>)}<SectionCard><div className="more-menu"><Link href="/settings"><i className="menu-gray"><UserRound /></i><span><strong>Akun Saya</strong><small>Profil dan keamanan akun</small></span><ChevronRight /></Link><a href="mailto:support@example.test"><i className="menu-blue"><CircleHelp /></i><span><strong>Pusat Bantuan</strong><small>Panduan dan kontak dukungan</small></span><ChevronRight /></a><button><i className="menu-red"><LogOut /></i><span><strong>Keluar</strong><small>Akhiri sesi di perangkat ini</small></span><ChevronRight /></button></div></SectionCard><p className="app-version">AICE Distributor DMS · Versi 0.1 Pilot</p></> }
